version: '3.8'

services:

  mysql:
    image: mysql:latest
    container_name: dev_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "dev_phpmyadmin"
    restart: always
    links:
      - mysql:db
    ports:
      - 8080:80
    environment:
      UPLOAD_LIMIT: 2G
      MEMORY_LIMIT: 2G
      MAX_EXECUTION_TIME: 600
      PMA_HOST: mysql
      PMA_PORT: 3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
